name: griger
permalink: /blog/:year/:month/:day/:title
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
        css_class: 'highlight'
